#!/bin/bash
# Script to configure Nginx to run as the nginx user and listen on port 8080
NGINX_CONF="/etc/nginx/nginx.conf"
sudo sed -i 's/^user .*/user nginx;/g' "$NGINX_CONF"
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80;/listen \[::\]:8080;/g' /etc/nginx/sites-enabled/default
sudo chown -R nginx:nginx /var/log/nginx /var/lib/nginx
sudo service nginx restart
