#!/usr/bin/env bash
# install nginx

apt-get -y update
apt-get -y install nginx
ufw enable
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
echo "Holberton School" > /tmp/correction/1111410300863801410678389961746095454313_5/2026/6349/web_server/index.html
service nginx restart
